#!/bin/bash

# get the latest iso
# fix this for artix
# curl http://www.gtlib.gatech.edu/pub/archlinux/iso/latest/ | awk {'print $6'} | awk -F'"' '{for(i=2;i<=NF;i+=2) print $i}' | grep --color=never "iso$" | while read file; do curl -O http://www.gtlib.gatech.edu/pub/archlinux/iso/latest/$file; done

# create the main disk
qemu-img create -f raw disk.img 20G

# # create any additional disks
# for i in {1..3}
# 	do qemu-img create -f raw -o preallocation=full disk${i}.img 8G
# done

# copy uefi vars to local folder
cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd uefi_vars.fd
