#!/bin/bash

# dir=${HOME}/vm/zfs
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

USERID=$(whoami)
precreation=$(ip tuntap list | cut -d: -f1 | sort)
sudo ip tuntap add user $USERID mode tap
postcreation=$(ip tuntap list | cut -d: -f1 | sort)
IFACE=$(comm -13 <(echo "$precreation") <(echo "$postcreation"))
echo "$IFACE"
sudo ip link set dev $IFACE master br0

# MACADDR="52:54:00:00:00:01"
MACADDR="52:54:00:00:00:01"

qemu-system-x86_64 \
	-m 8G \
	-enable-kvm \
	-cpu host \
	-smp 2 \
	-net nic,macaddr=$MACADDR \
	-net tap,ifname="$IFACE",script=no,downscript=no \
	-vga virtio -display gtk,gl=on \
	-drive format=raw,file=${dir}/disk.img,index=0,if=virtio \
	-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd \
	-drive if=pflash,format=raw,file=${dir}/uefi_vars.fd

	# -net user,hostfwd=tcp::2222-:22 \
	# -net tap,ifname="$IFACE",script=no,downscript=no \

# TODO Remove $IFACE as master to br0
sudo ip link set dev $IFACE down &> /dev/null
sudo ip tuntap del $IFACE mode tap &> /dev/null
